chat/project/forms.py
"""Forms for the chat app."""

from flask_wtf import FlaskForm
from wtforms.fields import EmailField, PasswordField, StringField, SubmitField
from wtforms.validators import EqualTo, InputRequired, Length

from .const import MAX_PASSWORD_LENGTH, MIN_PASSWORD_LENGTH


class SignupForm(FlaskForm):
    """Sign up form."""

    username = StringField("username", validators=[InputRequired(), Length(6, 64)])
    email = EmailField("email", validators=[InputRequired(), Length(1, 64)])
    password = PasswordField("password", validators=[InputRequired(), Length(MIN_PASSWORD_LENGTH, MAX_PASSWORD_LENGTH)])
    password2 = PasswordField("repeat password", validators=[EqualTo("pwd", message="Passwords must match!")])
    submit = SubmitField("Sign Up")


class LoginForm(FlaskForm):
    """Log in form."""

    email = StringField("username or email", validators=[InputRequired(), Length(1, 64)])
    password = PasswordField("password", validators=[InputRequired(), Length(MIN_PASSWORD_LENGTH, MAX_PASSWORD_LENGTH)])
    submit = SubmitField("Log In")


class SendForm(FlaskForm):
    """Form for sending a message."""

    message = StringField("message", validators=[InputRequired(), Length(1, 4096)])
    submit = SubmitField("Send")


class ContactForm(FlaskForm):
    """Form for adding a new contact."""

    email = EmailField("email", validators=[InputRequired(), Length(1, 64)])
    submit = SubmitField("Add Contact")

chat/project/__init__.py
"""Flask application module."""

import os

from flask import Flask

from .database import init_db
from .events import socketio
from .login import init_login
from .routes.admin import bp as admin_bp
from .routes.auth import bp as auth_bp
from .routes.chat import bp as chat_bp


def create_app() -> Flask:
    """Create an application instance."""

    app = Flask(__name__)
    app.config["SECRET_KEY"] = os.urandom(32)

    init_db(app)
    init_login(app)

    app.register_blueprint(chat_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(admin_bp)

    socketio.init_app(app)
    return app

chat/project/routes/admin.py
"""Module handling the admin routes."""

from typing import Union

from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required
from werkzeug.wrappers import Response

from ..database import is_admin

bp = Blueprint("admin", __name__)


@bp.route("/admin/")
@login_required
def admin() -> Union[Response, str]:
    """Render the admin page."""

    if is_admin(current_user):
        return render_template("admin/admin.html")

    return redirect(url_for("chat.chat"))

chat/project/routes/auth.py
"""Authentication routes module."""

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user
from werkzeug.wrappers import Response

from ..database import User, db, send_welcome_message
from ..forms import LoginForm, SignupForm

bp = Blueprint("auth", __name__)


@bp.route("/login/")
def login() -> str:
    """Render the login page."""
    return render_template("auth/login.html", form=LoginForm())


@bp.route("/login/", methods=["POST"])
def login_post() -> Response:
    """Handle the login request."""

    form = LoginForm(request.form)
    email = form.email.data
    password = form.password.data

    if "@" in email:
        user = User.query.filter_by(email=email).first()
    else:
        user = User.query.filter_by(username=email).first()

    if not user or user.password != password:
        flash("Invalid username/password combination")
        return redirect(url_for("auth.login"))

    else:
        login_user(user)
        return redirect(url_for("chat.chat"))


@bp.route("/signup/")
def signup() -> str:
    """Render the signup page."""
    return render_template("auth/signup.html", form=SignupForm())


@bp.route("/signup/", methods=["POST"])
def signup_post() -> Response:
    """Handle the signup request."""

    form = SignupForm(request.form)
    email = form.email.data
    username = form.username.data
    password = form.password.data

    if User.query.filter_by(email=email).first():
        flash("Email address already exists")
        return redirect(url_for("auth.signup"))

    if User.query.filter_by(username=username).first():
        flash("Username already exists")
        return redirect(url_for("auth.signup"))

    user = User(email=email, password=password, username=username)
    db.session.add(user)
    db.session.commit()

    send_welcome_message(user)

    login_user(user)
    return redirect(url_for("chat.chat"))


@bp.route("/logout/", methods=["POST"])
@login_required
def logout() -> Response:
    """Logout the current user."""

    logout_user()
    flash("You have been logged out.", "success")
    return redirect(url_for("auth.login"))

chat/project/routes/chat.py
"""Module handling the main application routes."""

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.wrappers import Response

from ..database import Contact, Message, User, db
from ..forms import ContactForm, SendForm

bp = Blueprint("chat", __name__)


@bp.route("/")
def index() -> Response:
    """Redirect logged users to the chat, others to the login page."""

    if current_user:
        return redirect(url_for("chat.chat", partner=""))
    else:
        return redirect(url_for("auth.login"))


@bp.route("/chat/")
@bp.route("/chat/<email>")
@login_required
def chat(email: str = "") -> str:
    """Render the chat page.

    Chat page can have a conversation
        - open - email is the email of the partner,
        - closed - email is empty,
    """

    contacts = Contact.query.filter_by(user_id=current_user.id).all()

    if not email:
        return render_template("chat/index.html", form=SendForm(), contacts=contacts, partner=None)

    partner = User.query.filter_by(email=email).first()
    if not partner:
        return render_template("chat/index.html", form=SendForm(), contacts=contacts, partner=None)

    sent = Message.query.filter_by(sender_id=current_user.id, recipient_id=partner.id)
    received = Message.query.filter_by(recipient_id=current_user.id, sender_id=partner.id)
    messages = sent.union(received).order_by(Message.timestamp).all()

    return render_template("chat/index.html", form=SendForm(), contacts=contacts, partner=partner, messages=messages)


@bp.route("/chat/<email>/data")
@login_required
def chat_data(email: str) -> object:
    """Return data about the current user and the current partner."""

    partner = User.query.filter_by(email=email).first()
    if not partner:
        return "Error: partner does not exist"

    return {
        "current_user": {
            "email": current_user.email,
            "username": current_user.username,
        },
        "partner": {"email": email, "username": partner.username},
    }


@bp.route("/contacts/", methods=["POST"])
@login_required
def contacts() -> Response:
    """Add a new contact to the database."""

    form = ContactForm(request.form)
    email = form.email.data

    partner = User.query.filter_by(email=email).first()

    if not partner:
        flash("User does not exist")
        return redirect(url_for("chat.chat"))

    contact = Contact.query.filter_by(user_id=current_user.id, partner_id=partner.id).first()

    if not contact:
        contact = Contact(user_id=current_user.id, partner_id=partner.id, last_message_id=None)
        db.session.add(contact)
        db.session.commit()

    return redirect(url_for("chat.chat", email=email))

chat/project/templates/chat/index.html
{% extends "layouts/chat.html" %}

{% block contacts %}

    {% for contact in contacts %}

        <a class="contact" href="{{ url_for('chat.chat', email=contact.partner.email) }}">
            <div class="name">{{ contact.partner.username }}</div>
            <div class="last_message">{{ contact.last_message.message }}</div>
            <div class="timestamp">{{ contact.last_message.timestamp }}</div>
        </a>
    {% endfor %}

{% endblock contacts %}

{% block chat %}
    {% if partner %}

        <div id="partner">
            {{ partner.username }}
        </div>

        <ul class="messages" id="messages">
            {% for message in messages %}
                {% if message.sender.email == current_user.email %}
                    <li class="message sent">
                        <div>
                            {{ message.sender.username }}: {{ message.message }}
                        </div>
                    </li>
                {% else %}
                    <li class="message received">
                        <div>
                            {{ message.sender.username }}: {{ message.message }}
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>

        <div class="input">
            <input type="text" id="message" placeholder="Message..."/>
            <button onclick="sendMessage()">Send</button>
        </div>

    {% endif %}
{% endblock chat %}

{% block search %}
    {% if partner %}

        <div class="input">
            <input type="text" id="search" placeholder="Message..."/>
            <button onclick="search()">Search</button>
        </div>

        <ul class="messages" id="found">

        </ul>
        
    {% endif %}
{% endblock search %}

chat/project/templates/elements/flashes.html
<div class="flashes">
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
</div>

chat/project/templates/elements/topbar.html
<a class="topbar-left" href="{{ url_for('chat.chat') }}">
	<img src="{{ url_for('static', filename='logo.svg') }}" width=256 height=256 alt="Vulpes Chat" />
	<h1>Vulpes Chat</h1>
</a>

<div class="topbar-right">
	<div id="current_user">
		{{ current_user.username }} ({{ current_user.email }})
	</div>
	<form action="{{ url_for('auth.logout') }}" method="post">
		<input id="logout" class="button" type="submit" value="Logout" />
	</form>
</div>

chat/project/templates/layouts/auth.html
{% extends "layouts/base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='auth.css') }}" />
{% endblock head %}

{% block body %}

    <div class="auth">
        <img src="{{ url_for('static', filename='logo.svg') }}" width=256 height=256 alt="Vulpes Mail" />
        {% block content %}{% endblock content %}
    </div>

{% endblock body %}

chat/project/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Vulpes Chat</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />

        {% block head %}{% endblock head %}
    </head>

    <body>

        {% include "elements/flashes.html" %}
        {% block body %}{% endblock body %}

    </body>

</html>

chat/project/templates/layouts/chat.html
{% extends "layouts/base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='chat.css') }}" />
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='chat.js') }}"></script>
{% endblock head %}

{% block body %}

    <nav class="topbar">
        {% include "elements/topbar.html" %}
    </nav>

    <main>

        <nav class="sidebar" id="contacts">

            <div class="contact">

                <div>Add Contact</div>

                <form class="input" action="{{ url_for('chat.contacts') }}" method="post">
                    <input type="email" name="email" placeholder="Email Address" />
                    <input class="button" type="submit" value="Add" />
                </form>
            </div>

            {% block contacts %} {% endblock contacts %}

        </nav>
    
        <div id="chat">
            {% block chat %} {% endblock chat %}
        </div>

        <div id="searchbox">
            {% block search %} {% endblock search %}
        </div>
    </main>

{% endblock body %}