index/project/__init__.py
"""Flask application module."""

import os

from flask import Flask

from .routes import bp


def create_app() -> Flask:
    """Create a Flask application."""

    app = Flask(__name__)
    app.config["SECRET_KEY"] = os.urandom(32)

    app.register_blueprint(bp)

    return app

index/project/routes.py
"""Routes module."""

from os import environ
from typing import Union

from flask import Blueprint, redirect, render_template, url_for
from werkzeug import Response

from .data import apps, tasks, vulns

bp = Blueprint("routes", __name__)


@bp.route("/")
def index() -> str:
    """Index page."""
    return render_template("index.html", apps=apps, vulns=vulns, tasks=tasks, environ=environ)


@bp.route("/404")
def not_found() -> str:
    """404 page."""
    return render_template("404.html")


@bp.route("/vuln/<id>")
def vuln(id: str) -> Union[Response, str]:
    """Vulnerability page."""
    if id not in vulns:
        return redirect(url_for("routes.index"))
    return render_template(f"vulns/{id}.html")


@bp.route("/task/<id>/")
def task(id: str) -> Response:
    """Render the page."""
    if id not in tasks:
        return redirect(url_for("routes.index"))
    return redirect(url_for("routes.step", id=id, i=1))


@bp.route("/task/<id>/<int:i>/")
def step(id: str, i: int) -> Union[Response, str]:
    """Render the task step page."""

    step_count = int(tasks[id]["steps"])  # type: ignore[call-overload]

    if id in tasks and 1 <= i <= step_count:
        return render_template(f"tasks/{id}/{i}.html", id=id, i=i, len=tasks[id]["steps"], environ=environ)

    return redirect(url_for("routes.index"))


@bp.route("/fake-login/")
def fake_login() -> str:
    """Get the URL of the fake login page."""
    return environ["ATTACKER_URL"] + "/upgrade/"

index/project/templates/elements/banner-app.html
<div class="banner">
    <h3>{{ app.name }}</h3>

    {% for lang, text in app.desc.items() %}
        <div class="lang {{ lang }}">{{ text }}</div>
    {% endfor %}

    <div class="link-wrapper">
        <a class="lang en" href="{{ environ.get(app.link, '/404') }}">Visit the app</a>
        <a class="lang cs" hidden href="{{ environ.get(app.link, '/404') }}">Navštívit</a>
    </div>
</div>

index/project/templates/elements/banner-task.html
<div class="banner">
    <h3>{{ task.name }}</h3>

    {% for lang, text in task.desc.items() %}
        <div class="lang {{ lang }}">{{ text }}</div>
    {% endfor %}

    <div class="link-wrapper">
        <a class="lang en" href="{{ url_for('routes.task', id=id) }}">Try it yourself</a>
        <a class="lang cs" hidden href="{{ url_for('routes.task', id=id) }}">Vyzkoušet</a>
    </div>
</div>

index/project/templates/elements/banner-vuln.html
<div class="banner">
    <h3>{{ vuln.name }}</h3>

    {% for lang, text in vuln.desc.items() %}
        <div class="lang {{ lang }}">{{ text }}</div>
    {% endfor %}

    <div class="link-wrapper">
        <a class="lang en" href="{{ url_for('routes.vuln', id=id) }}">Learn more</a>
        <a class="lang cs" hidden href="{{ url_for('routes.vuln', id=id) }}">Zjistit víc</a>
    </div>
</div>

index/project/templates/tasks/phish/1.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Account creation</div>
	<div class="lang cs">Vytvoření účtu</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">Create a mail account in the <a href="{{ environ['MAIL_URL'] }}">Vulpes Mail</a> application.</div>
	<div class="lang cs">Vytvořte si účet v aplikaci <a href="{{ environ['MAIL_URL'] }}">Vulpes Mail</a>.</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">Visit the <a href="{{ environ['MAIL_URL'] + '/login/' }}">login page</a>, come up with a username and password and sign up.</div>
	<div class="lang cs">Navštivte <a href="{{ environ['MAIL_URL'] + '/login/' }}">přihlašovací stránku</a>, zvolte si uživatelské jméno a heslo a zaregistrujte se.</div>
{% endblock help %}

{% block extra %}
	<p class="lang en">Please enter your email address.</p>
	<p class="lang cs">Prosím zadejte svou emailovou adresu.</p>

	<input id="email" name="email" type="email" placeholder="Email" />
	<input id="url" name="url" type="hidden" value="{{ environ['ATTACKER_URL'] }}/upgrade/" />

	<button class="lang en send">Send</button>
	<button class="lang cs send">Odeslat</button>

{% endblock extra %}

index/project/templates/tasks/phish/2.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Receiving mail</div>
	<div class="lang cs">Přijetí mailu</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">Wait until you receive a mail from someone.</div>
	<div class="lang cs">Počkejte, až vám od někoho přijde mail.</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">There is an Inbox button on the left panel, then try to refresh the page.</div>
	<div class="lang cs">Na levém panelu je tlačítko Inbox, případně zkuste stránku obnovit.</div>
{% endblock help %}

index/project/templates/tasks/phish/3.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Account upgrade</div>
	<div class="lang cs">Vylepšení účtu</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">The received email should offer you an account upgrade, check it out.</div>
	<div class="lang cs">Příchozí mail by vám měl nabídnout vylepšení účtu, zkuste to.</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">Open the email you just received and click on the link.</div>
	<div class="lang cs">Otevřete email, který vám právě přišel a klikněte na odkaz.</div>
{% endblock help %}

index/project/templates/tasks/phish/4.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Logging in</div>
	<div class="lang cs">Přihlášení</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">It looks like we should log in. It's a bit suspicious that the link from the received email leads to the login page. But let's try it.</div>
	<div class="lang cs">Vypadá to, že se máme přihlásit. Je trochu podezřelé, že odkaz z přijatého mailu vede na přihlašovací stránku. Ale pojďme to zkusit.</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">Enter your username and password and click on the Login button.</div>
	<div class="lang cs">Zadejte své uživatelské jméno a heslo a klikněte na tlačítko Login.</div>
{% endblock help %}

index/project/templates/tasks/phish/5.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Did something happen?</div>
	<div class="lang cs">Stalo se něco?</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">It doesn't look like we have an upgraded account, we are just logged in to the mail application. Try to look at the link in the received mail again. Is there something strange about it?</div>
	<div class="lang cs">Nevypadá to, že bychom měli vylepšený účet, pouze jsme přihášeni v mailové aplikaci. Zkuste se znovu kouknout na odkaz v přijatém mailu. Je na něm něco divného?</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">Open the received email and check the link you clicked on. Does it really lead to the login page of the mail application?</div>
	<div class="lang cs">Rozklikněte přijatý email a zkontrolujte odkaz, na který jste kliknuli. Vede opravdu na přihlašovací stránku mailové aplikace?</div>
{% endblock help %}

index/project/templates/tasks/phish/6.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Password breach</div>
	<div class="lang cs">Prozrazení hesla</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">
		The link actually didn't lead to the login page of the real mail application, but to a fake page that looked the same.
		Your login credentials could have been recorded. Check the Attacker application if your password is there.
	</div>
	<div class="lang cs">
		Odkaz ve skutečnosti nevedl na přihlašovací stránku opravdové mailové aplikace, ale na falešnou stránku vypadající stejně.
		Vaše přihlašovací údaje tak mohly být zaznamenány. Podívejte se do Attacker aplikace, zda má vaše heslo.
	</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">Visit {{ environ['ATTACKER_URL'] }} and check if stolen credentials contain your password.</div>
	<div class="lang cs">Navštivte {{ environ['ATTACKER_URL'] }} a zkontrolujte, zda je mezi ukradenými hesly i to vaše.</div>
{% endblock help %}

index/project/templates/tasks/phish/7.html
{% extends "tasks/phish/base.html" %}

{% block task %}
	<div class="lang en">Conclusion</div>
	<div class="lang cs">Závěrem</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">
		Be careful with suspicious links sent to you by a stranger.
		If you use a password manager / browser password save option, the login details will not be filled in on the fake page.
		And if you still log in to the fake page, change your password as soon as possible.
	</div>
	<div class="lang cs">
		Dávejte pozor na podezřelé odkazy, které vám zaslala cizí osoba.
		Pokud používáte správce hesel / možnost v prohlížeči heslo uložit, přihlašovací údaje se na falešné stránce samy nevyplní.
		A pokud se přeci jen na falešné stránce přihlásíte, změňte si co nejdříve heslo.
	</div>
{% endblock goal %}

index/project/templates/tasks/phish/base.html
{% extends "layouts/task.html" %}

{% block title %}Phishing{% endblock title %}
{% block name %}Phishing{% endblock name %}

{% block overview %}
	<div class="lang en">Easiest social engineering attack.</div>
	<div class="lang cs" hidden>Zneužití sociálních vztahů.</div>
{% endblock overview %}

index/project/templates/tasks/sql2/1.html
{% extends "tasks/sql2/base.html" %}

{% block task %}
	<div class="lang en">Suggestion</div>
	<div class="lang cs">Doporučení</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">Read the overview of SQL injection and try out the SQL OR Injection and Unicode demonstrations.</div>
	<div class="lang cs">Přečtěte si přehled SQL injection a projděte si demonstraci SQL OR Injection a demonstraci Unicode.</div>
{% endblock goal %}

index/project/templates/tasks/sql2/2.html
{% extends "tasks/sql2/base.html" %}

{% block task %}
	<div class="lang en">Logging in</div>
	<div class="lang cs">Přihlášení</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">Log in to the Vulpes Chat application and click on a conversation.</div>
	<div class="lang cs">Přihlaste se do aplikace Vulpes Chat a rozklikněte nějakou konverzaci.</div>
{% endblock goal %}

index/project/templates/tasks/sql2/3.html
{% extends "tasks/sql2/base.html" %}

{% block task %}
	<div class="lang en">Database schema</div>
	<div class="lang cs">Schéma databáze</div>
{% endblock task %}

{% block goal %}
	<div class="lang cs">Vzpoměňte si, jak vypadá schéma databáze. Bude to potřeba k provedení útoku SQL Injection.</div>
	<div class="lang en">Remember how the database schema looks like. It will be needed to perform the SQL Injection attack.</div>
{% endblock goal %}

{% block help %}
	<div class="lang cs">Projděte si demonstrací Unicode - ke schématu máte přístup na administrační stránce aplikace Vulpes Chat.</div>
	<div class="lang en">Go through the Unicode demonstration - you have access to the schema on the admin page of the Vulpes Chat application.</div>
{% endblock help %}

index/project/templates/tasks/sql2/4.html
{% extends "tasks/sql2/base.html" %}

{% block task %}
	<div class="lang en">Information gathering</div>
	<div class="lang cs">Zjištění informací</div>
{% endblock task %}

{% block goal %}
	<div class="lang cs">
		Ujistěte se, že rozumíte SQL Injection. 
		Zkuste provést vsunutí UNION SELECT do vyhledávacího pole konverzace.
		Dejte pozor na to, že počet sloupců na levé straně (<code>message</code>) musí být stejný jako počet sloupců na pravé straně (<code>user</code>).
		Měli byste být schopni zjistit, jaká hesla používaji Alice a Bob.
	</div>
	<div class="lang en">
		Make sure you understand SQL Injection.
		Try to perform UNION SELECT injection in the search box of any conversation.
		Note that the number of columns on the left side (<code>message</code>) must be the same as the number of columns on the right side (<code>user</code>).
		You should be able to find out what passwords Alice and Bob use.
	</div>
{% endblock goal %}

{% block help %}
	<div class="lang en">Try entering the following into the search box: <code>%' UNION SELECT 1, username || ' - ' || password, 1, 1, 1 FROM user --</code>.</div>
	<div class="lang cs">Zkuste do vyhledávacího pole zadat: <code>%' UNION SELECT 1, username || ' - ' || password, 1, 1, 1 FROM user --</code></div>
{% endblock help %}

index/project/templates/tasks/sql2/5.html
{% extends "tasks/sql2/base.html" %}

{% block task %}
	<div class="lang en">Conclusion</div>
	<div class="lang cs">Závěrem</div>
{% endblock task %}

{% block goal %}
	<div class="lang en">If you found out that Alice has the password alice123lidell and Bob bob123hatter, congratulations. You have performed a UNION SELECT injection.</div>
	<div class="lang cs">Pokud jste zjistili, že Alice má heslo alice123lidell a Bob bob123hatter, gratulujeme. Provedli jste UNION SELECT injection.</div>
{% endblock goal %}

index/project/templates/tasks/sql2/base.html
{% extends "layouts/task.html" %}

{% block title %}SQL UNION SELECT Injection{% endblock title %}
{% block name %}SQL UNION SELECT Injection{% endblock name %}

{% block overview %}
	<div class="lang en">How to access data from other tables in the database?</div>
	<div class="lang cs" hidden>Jak získat data z jiných tabulek databáze?</div>
{% endblock overview %}