shop/project/routes/shop.py
"""Module handling the shop routes."""

from typing import Dict, Tuple

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_cors import cross_origin
from flask_login import current_user, login_required
from werkzeug import Response

from ..database import Order, OrderItem, Product, Review, db
from ..forms import CartForm, DetailsForm, ReviewForm

bp = Blueprint("shop", __name__)


carts: Dict[str, Dict[str, Tuple[Product, int]]] = {}


@bp.route("/")
def index() -> str:
    """Render the shop index page."""
    products = Product.query.all()
    return render_template("shop/index.html", products=products)


@bp.route("/product/<product_url>/")
def product(product_url: str) -> str:
    """Render the product page."""
    product = Product.query.filter_by(url=product_url).first()
    return render_template("shop/product.html", product=product, form=ReviewForm())


@bp.route("/product/<product_url>/", methods=["POST"])
def reviews(product_url: str) -> str:
    """Add a review for a product.

    Returns: The review template.
    """

    form = ReviewForm(request.form)
    product = Product.query.filter_by(url=product_url).first()
    review = Review(text=form.text.data, product_id=product.id)
    db.session.add(review)
    db.session.commit()

    return render_template("elements/review.html", review=review)


@bp.route("/cart/")
@login_required
def cart() -> str:
    """Render the cart page."""

    uid = current_user.email
    products = carts.get(uid, {}).values()
    total = sum(product.price * quantity for product, quantity in products)

    return render_template("shop/cart.html", products=products, total=total)


@bp.route("/cart/", methods=["POST"])
@cross_origin()
@login_required
def cart_post() -> Response:
    """Add a product to the cart."""

    form = CartForm(request.form)
    product_url = form.product_url.data
    quantity = form.quantity.data
    product = Product.query.filter_by(url=product_url).first()

    uid = current_user.email

    if uid not in carts:
        carts[uid] = {}

    current_quantity = carts[uid][product_url][1] if product_url in carts[uid] else 0
    carts[uid][product_url] = (product, current_quantity + quantity)

    flash(f"{product.name} added to cart.")
    return redirect(url_for("shop.cart"))


@bp.route("/cart/", methods=["DELETE"])
@login_required
def cart_delete() -> str:
    """Remove a product from the cart."""

    form = CartForm(request.form)
    product_url = form.product_url.data

    uid = current_user.email
    del carts[uid][product_url]

    flash("Item removed from cart.")
    return render_template("elements/flashes.html")


@bp.route("/cart/", methods=["PUT"])
@login_required
def cart_put() -> str:
    """Update the quantity of a product in the cart."""

    form = CartForm(request.form)
    product_url = form.product_url.data
    quantity = form.quantity.data

    uid = current_user.email
    product, _ = carts[uid][product_url]
    carts[uid][product_url] = (product, quantity)
    flash(f"{product.name} quantity updated.")
    return render_template("elements/flashes.html")


@bp.route("/checkout/")
@login_required
def checkout() -> str:
    """Render the checkout page."""
    return render_template("shop/checkout.html", form=DetailsForm())


@bp.route("/checkout/", methods=["POST"])
@login_required
def checkout_post() -> Response:
    """Checkout the cart."""

    form = DetailsForm(request.form)
    user = current_user
    uid = user.email

    user.first_name = form.first_name.data
    user.last_name = form.last_name.data
    user.address = form.address.data
    user.city = form.city.data
    db.session.commit()

    cart = carts[uid]

    if not cart:
        flash("Your cart is empty.")
        return redirect(url_for("shop.cart"))

    total = sum(product.price * quantity for product, quantity in cart.values())
    order = Order(user_id=user.id, total=total)

    db.session.add(order)
    db.session.commit()

    for product, quantity in cart.values():
        order_item = OrderItem(order_id=order.id, product_id=product.id, quantity=quantity)
        db.session.add(order_item)
        db.session.commit()

    del carts[uid]

    flash("Order placed successfully.")
    return redirect(url_for("shop.index"))

shop/project/templates/shop/cart.html
{% extends "layouts/shop.html" %}
{% block content %}

	<h2>Cart</h2>

	<div id="cart-list">
		{% for product, quantity in products %}
			{% include "elements/cart-item.html" %}
		{% endfor %}
	</div>
		
	<div id="summary" class="column">
		{% if not products %}
			<p id="empty">Your cart is empty</p>
		{% else %}
			<div class="row">
				Total: <p id="total">{{ '%0.2f' | format(total) }}</p> $
			</div>
			<a class="button" href="{{ url_for('shop.checkout') }}">Checkout</a>
		{% endif %}
	</div>
		
{% endblock content %}

shop/project/templates/shop/checkout.html
{% extends "layouts/shop.html" %}
{% block content %}

<h2>Checkout</h2>

<form id="checkout" class="column" method="post">

	{% if current_user.is_authenticated %}
		{{ form.email(placeholder="Email", value=current_user.email) }}
		{{ form.first_name(placeholder="First name", value=current_user.first_name) }}
		{{ form.last_name(placeholder="Last name", value=current_user.last_name) }}
		{{ form.address(placeholder="Address", value=current_user.address) }}
		{{ form.city(placeholder="City", value=current_user.city) }}
	{% else %}
		{{ form.email(placeholder="Email") }}
		{{ form.first_name(placeholder="First name") }}
		{{ form.last_name(placeholder="Last name") }}
		{{ form.address(placeholder="Address") }}
		{{ form.city(placeholder="City") }}
	{% endif %}

	<button type="submit">Submit</button>

</form>

{% endblock content %}

shop/project/templates/shop/index.html
{% extends "layouts/shop.html" %}
{% block content %}

	<h2>Products</h2>

	<div class="products">
		{% for product in products %}
			<a class="product" href="{{ url_for('shop.product', product_url=product.url) }}">
				<img src="{{ url_for('static', filename='products/' + product.url + '.jpg') }}" width=256 height=256 alt="{{ product.name }}" />
				<h3 class="name">{{ product.name }}</h3>
				<p class="description">{{ product.description }}</p>
				<p class="price">{{ product.price }} $</p>
			</a>
		{% endfor %}
	</div>

{% endblock content %}

shop/project/templates/shop/product.html
{% extends "layouts/shop.html" %}
{% block content %}

	<div class="overview">

		<div class="image">
			<img src="{{ url_for('static', filename='products/' + product.url + '.jpg') }}" width=256 height=256 alt="{{ product.name }}" />
		</div>
		<div class="info">
			<div class="description">
				<h2>{{ product.name }}</h2>
				
				<p>{{ product.description }}</p>
				<p class="price">{{ product.price }} $</p>
			</div>

			<form action="{{ url_for('shop.cart_post') }}" method="post">
				<input type="hidden" name="product_url" value="{{ product.url }}" />
				<input type="number" name="quantity" value="1" min="1" max="100" />
				<button type="submit">Add to cart</button>
			</form>	
		</div>
	</div>

	<div class="reviews">
		<h3>Reviews</h3>

		<div id="reviews">
			{% if not product.reviews %}
				<p id="empty">No reviews yet</p>
			{% endif %}
			{% for review in product.reviews %}
				{% include "elements/review.html" %}
			{% endfor %}
		</div>

		<div class="input">
            <input type="text" id="review" placeholder="Write a review..."/ />
            <button onclick="addReview()">Add</button>
        </div>
	</div>

{% endblock content %}